# Generated by Django 3.2 on 2022-12-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttgen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='Desig',
            field=models.CharField(choices=[('Asst Prof', 'Asst Prof'), ('Prof', 'Prof'), ('Asso Prof', 'Asso Prof')], default='Asst Prof', max_length=25),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Theory', 'Theory'), ('Lab', 'Lab')], default='Theory', max_length=25),
        ),
    ]
