# Generated by Django 3.2 on 2023-01-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttgen', '0002_auto_20221228_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtime',
            name='time',
            field=models.CharField(choices=[('7:30 - 8:30', '7:30 - 8:30'), ('8:30 - 9:30', '8:30 - 9:30'), ('9:30 - 10:30', '9:30 - 10:30'), ('10:30 - 11:30', '10:30 - 11:30'), ('11:30 - 12:30', '11:30 - 12:30'), ('12:30 - 1:30', '12:30 - 1:30'), ('2:30 - 3:30', '2:30 - 3:30'), ('3:30 - 4:30', '3:30 - 4:30'), ('4:30 - 5:30', '4:30 - 5:30')], default='11:30 - 12:30', max_length=50),
        ),
        migrations.AlterModelTable(
            name='room',
            table='Room',
        ),
    ]
