# Generated by Django 3.2 on 2023-01-03 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttgen', '0003_auto_20230103_2236'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='Courses',
        ),
        migrations.AlterModelTable(
            name='department',
            table='Department',
        ),
        migrations.AlterModelTable(
            name='instructor',
            table='Faculty',
        ),
        migrations.AlterModelTable(
            name='meetingtime',
            table='Class Timing',
        ),
        migrations.AlterModelTable(
            name='section',
            table='Section',
        ),
    ]
