# Generated by Django 3.2 on 2023-01-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttgen', '0005_auto_20230103_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtime',
            name='dept',
            field=models.CharField(choices=[('IS_SEM_3', 'IS_SEM_3'), ('IS_SEM_5', 'IS_SEM_5'), ('IS_SEM_7', 'IS_SEM_7'), ('CSBS_SEM_1', 'CSBS_SEM_1'), ('CSBS_SEM_3', 'CSBS_SEM_3'), ('CSBS_SEM_5', 'CSBS_SEM_5'), ('CSBS_SEM_7', 'CSBS_SEM_7')], default='IS_SEM_3', max_length=15),
        ),
    ]
