# Generated by Django 3.2 on 2023-01-04 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttgen', '0007_remove_course_max_numb_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='seating_capacity',
        ),
    ]
