# Generated by Django 3.2 on 2023-01-04 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttgen', '0008_remove_room_seating_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='instructors',
            new_name='instructor',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='uid',
            new_name='t_id',
        ),
        migrations.RenameField(
            model_name='meetingtime',
            old_name='pid',
            new_name='m_id',
        ),
    ]
