# Generated by Django 3.2 on 2023-01-05 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttgen', '0010_auto_20230105_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingtime',
            name='dept',
        ),
    ]
